CREATE DATABASE BUSANGIANTS;
USE BUSANGIANTS;

CREATE TABLE ADMIN(
	ADMIN_ID	VARCHAR(20),
	NICK_NAME	VARCHAR(20),
	ADMIN_PW	VARCHAR(20),
	ADMIN_NM	VARCHAR(20),
	JOIN_DT		TIMESTAMP

);

CREATE TABLE MEMBER(
	MEMBER_ID			VARCHAR(20),
	MEMBER_NM			VARCHAR(50),
	MEMBER_NICK_NAME	VARCHAR(10),
	MEMBER_PW			VARCHAR(20),
	SEX					VARCHAR(10),
	DATE_BIRTH			VARCHAR(20),
	PHONE_NO			VARCHAR(20),
	EMAIL				VARCHAR(20),
	ZIPCODE				VARCHAR(20),
	ROAD_ADDRESS		VARCHAR(500),
	JIBUN_ADDRESS		VARCHAR(500),
	JOIN_DT				TIMESTAMP
	
);

CREATE TABLE NOTICE(
	NOTICE_NO			VARCHAR(5000),
	NOTICE_TITLE		VARCHAR(50),
	NOTICE_CONTENTS		VARCHAR(500),
	NOTICE_FILE			VARCHAR(5000),
	NOTICE_READ_CNT		VARCHAR(5000),
	NOTICE_REGISTER_DT	TIMESTAMP
	
);

CREATE TABLE BOARD(
	BOARD_NO			VARCHAR(5000),
	BOARD_ NICKNAME		VARCHAR(10),
	BOARD_TITLE			VARCHAR(50),
	BOARD_CONTENTS		VARCHAR(500),
	BOARD_FILE			VARCHAR(500),
	BOARD_READ_CNT		VARCHAR(5000),
	BOARD_REGISTER_DT	TIMESTAMP

);

CREATE TABLE COMMENT(
	COMMENT_NO			VARCHAR(5000),
	COMMENT_NICKNAME	VARCHAR(10),
	COMMENT_CONTENTS	VARCHAR(500),
	COMMENT_READ_CNT	VARCHAR(5000),
	COMMENT_REGISTER_DT	TIMESTAMP

);

CREATE TABLE SCORE(
	SCORE_NO			VARCHAR(5000),
	SCORE_NICKNAME		VARCHAR(20),
	SCORE_TITLE			VARCHAR(50),
	SCORE_FILE			VARCHAR(500),
	SCORE_READ_CNT		VARCHAR(5000),
	SCORE_REGISTER_DT	TIMESTAMP

);

CREATE TABLE MATCHES(
	MATCHES_NO			VARCHAR(50),
	MATCHES_NICKNAME	VARCHAR(20),
	MATCHES_FILE		VARCHAR(500),
	MATCHES_READ_CNT	VARCHAR(5000),
	MATCHES_REGISTER_DT	TIMESTAMP

);

CREATE TABLE HIGHLIGHT(
	HIGHLIGHT_NO			VARCHAR(5000),
	HIGHLIGHT_NICKNAME		VARCHAR(20),
	HIGHLIGHT_TITLE			VARCHAR(50),
	HIGHLIGHT_FILE			VARCHAR(500),
	HIGHLIGHT_READ_CNT		VARCHAR(5000),
	HIGHLIGHT_REGISTER_DT	TIMESTAMP

);

CREATE TABLE REGISTRATION(
	REGISTRATION_NO				VARCHAR(5000),
	REGISTRATION_NICKNAME		VARCHAR(20),
	REGISTRATION_TITLE			VARCHAR(50),
	REGISTRATION_CONTENT		VARCHAR(500),
	REGISTRATION_FILE			VARCHAR(500),
	REGISTRATION_READ_CNT		VARCHAR(5000),
	REGISTRATION_REGISTER_DT	TIMESTAMP
	

);